import { StyleSheet, Dimensions } from 'react-native';
import { COLORS, FONT_SIZES, SPACING, normaSizes } from '../constants';

const { width } = Dimensions.get('window');

export const createLojaCreateEditStyles = () => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: COLORS.white,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.sm,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.grayLight,
      backgroundColor: COLORS.white,
      elevation: 2,
      shadowColor: COLORS.black,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.1,
      shadowRadius: 2,
    },
    headerTitle: {
      fontSize: normaSizes(FONT_SIZES.lg),
      fontWeight: 'bold',
      color: COLORS.dark,
      marginLeft: SPACING.sm,
    },
    saveButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.sm,
      backgroundColor: COLORS.primary,
      borderRadius: 8,
    },
    saveButtonText: {
      color: COLORS.white,
      fontSize: normaSizes(FONT_SIZES.sm),
      fontWeight: 'bold',
      marginLeft: SPACING.xs,
    },
    scrollContainer: {
      flexGrow: 1,
      padding: SPACING.md,
    },
    formSection: {
      marginBottom: SPACING.xl,
    },
    sectionTitle: {
      fontSize: normaSizes(FONT_SIZES.lg),
      fontWeight: 'bold',
      color: COLORS.dark,
      marginBottom: SPACING.md,
    },
    logoSection: {
      alignItems: 'center',
      marginBottom: SPACING.xl,
      paddingVertical: SPACING.lg,
      backgroundColor: COLORS.light,
      borderRadius: 12,
    },
    logoContainer: {
      position: 'relative',
      marginBottom: SPACING.md,
    },
    logoImage: {
      width: 120,
      height: 120,
      borderRadius: 12,
      backgroundColor: COLORS.white,
      borderWidth: 2,
      borderColor: COLORS.grayLight,
    },
    logoPlaceholder: {
      width: 120,
      height: 120,
      borderRadius: 12,
      backgroundColor: COLORS.white,
      borderWidth: 2,
      borderColor: COLORS.grayLight,
      borderStyle: 'dashed',
      justifyContent: 'center',
      alignItems: 'center',
    },
    logoPlaceholderText: {
      fontSize: normaSizes(FONT_SIZES.sm),
      color: COLORS.gray,
      textAlign: 'center',
      marginTop: SPACING.xs,
    },
    editLogoButton: {
      position: 'absolute',
      bottom: -8,
      right: -8,
      backgroundColor: COLORS.primary,
      borderRadius: 20,
      padding: SPACING.xs,
      borderWidth: 2,
      borderColor: COLORS.white,
    },
    uploadButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: SPACING.lg,
      paddingVertical: SPACING.md,
      backgroundColor: COLORS.primary + '20',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: COLORS.primary,
    },
    uploadButtonText: {
      color: COLORS.primary,
      fontSize: normaSizes(FONT_SIZES.md),
      fontWeight: 'bold',
      marginLeft: SPACING.sm,
    },
    inputGroup: {
      marginBottom: SPACING.lg,
    },
    label: {
      fontSize: normaSizes(FONT_SIZES.md),
      fontWeight: 'bold',
      color: COLORS.dark,
      marginBottom: SPACING.sm,
    },
    requiredLabel: {
      color: COLORS.danger,
    },
    input: {
      borderWidth: 1,
      borderColor: COLORS.grayLight,
      borderRadius: 8,
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.sm,
      fontSize: normaSizes(FONT_SIZES.md),
      color: COLORS.dark,
      backgroundColor: COLORS.white,
      minHeight: 44,
    },
    inputError: {
      borderColor: COLORS.danger,
      borderWidth: 2,
    },
    textArea: {
      height: 100,
      textAlignVertical: 'top',
    },
    errorText: {
      fontSize: normaSizes(FONT_SIZES.sm),
      color: COLORS.danger,
      marginTop: SPACING.xs,
    },
    phoneContainer: {
      flexDirection: 'row',
      gap: SPACING.md,
    },
    phoneInput: {
      flex: 1,
    },
    selectButton: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: COLORS.grayLight,
      borderRadius: 8,
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.sm,
      backgroundColor: COLORS.white,
      minHeight: 44,
    },
    selectButtonError: {
      borderColor: COLORS.danger,
      borderWidth: 2,
    },
    selectButtonText: {
      fontSize: normaSizes(FONT_SIZES.md),
      color: COLORS.dark,
    },
    selectPlaceholder: {
      color: COLORS.gray,
    },
    statusSection: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: SPACING.md,
      paddingHorizontal: SPACING.md,
      backgroundColor: COLORS.light,
      borderRadius: 8,
      marginBottom: SPACING.lg,
    },
    statusLabel: {
      fontSize: normaSizes(FONT_SIZES.md),
      fontWeight: 'bold',
      color: COLORS.dark,
    },
    statusBadge: {
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.sm,
      borderRadius: 12,
      minWidth: 70,
      alignItems: 'center',
    },
    statusText: {
      fontSize: normaSizes(FONT_SIZES.sm),
      fontWeight: 'bold',
      color: COLORS.white,
    },
    previewContainer: {
      backgroundColor: COLORS.light,
      borderRadius: 12,
      padding: SPACING.md,
      marginBottom: SPACING.xl,
    },
    previewTitle: {
      fontSize: normaSizes(FONT_SIZES.md),
      fontWeight: 'bold',
      color: COLORS.dark,
      marginBottom: SPACING.md,
      textAlign: 'center',
    },
    previewCard: {
      backgroundColor: COLORS.white,
      borderRadius: 8,
      padding: SPACING.md,
      borderWidth: 1,
      borderColor: COLORS.grayLight,
    },
    previewHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: SPACING.sm,
    },
    previewLogo: {
      width: 60,
      height: 60,
      borderRadius: 8,
      backgroundColor: COLORS.grayLight,
      marginRight: SPACING.md,
    },
    previewInfo: {
      flex: 1,
    },
    previewNome: {
      fontSize: normaSizes(FONT_SIZES.md),
      fontWeight: 'bold',
      color: COLORS.dark,
      marginBottom: SPACING.xs,
    },
    previewEndereco: {
      fontSize: normaSizes(FONT_SIZES.sm),
      color: COLORS.gray,
      marginBottom: SPACING.xs,
    },
    previewCidade: {
      fontSize: normaSizes(FONT_SIZES.sm),
      color: COLORS.grayDark,
      fontWeight: '500',
    },
    previewContacts: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: SPACING.sm,
      marginBottom: SPACING.sm,
    },
    previewContact: {
      fontSize: normaSizes(FONT_SIZES.xs),
      color: COLORS.gray,
    },
    previewDescricao: {
      fontSize: normaSizes(FONT_SIZES.sm),
      color: COLORS.gray,
      lineHeight: 18,
      marginBottom: SPACING.sm,
    },
    loadingContainer: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: COLORS.white + 'CC',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1000,
    },
    loadingText: {
      marginTop: SPACING.sm,
      fontSize: normaSizes(FONT_SIZES.md),
      color: COLORS.gray,
      textAlign: 'center',
    },
  });
};